
library(plyr)
library(dplyr)
library(countrycode)
library(tidyr)
library(readxl)
library(janitor)
library(ggplot2)
library(skimr)
library(stringr)
library(ggrepel)

install.packages("countrycode")
library(countrycode)


country_emissions_filename <- "data/raw/CAIT-Country-CO2-Emissions-Energy-Sub-Sector.csv"

# Value added reflects the value generated by producing goods and services, 
# Value Added = (value of output - value of intermediate consumption)/total value added)
activity_value_filename <- "data/raw/value_added_per_act.csv"

regulation_filename <- "data/raw/law_search/data.csv"

emission_tax_filename <- "data/raw/emission_tax.csv"

processCsvData <- function(csv_filename) {
  csv_df <- read.csv(csv_filename) %>% 
    clean_names() %>% 
    na.omit()
  return(csv_df)
}

# Country Emission DF
ce_df <- processCsvData(country_emissions_filename)

# Regulation per country DF
reg_df <- processCsvData(regulation_filename)

# Emission tax per country DF
em_tax_df <- processCsvData(emission_tax_filename) %>% 
  dplyr::rename(year = time) %>% 
  select(-starts_with("indicator")) %>%
  dplyr::mutate(location = countrycode::countrycode(location, 'iso3c', 'country.name.en'))

# Per Country Activity Value Added DF
coun_ava_df <- processCsvData(activity_value_filename) %>% 
  dplyr::rename(activity = subject) %>% 
  dplyr::rename(year = time) %>% 
  select(-starts_with("indicator")) %>% # Remove Indicator 
  dplyr::mutate(location = countrycode::countrycode(location, 'iso3c', 'country.name.en'))

coun_ava_df$activity<- plyr::revalue(coun_ava_df$activity, c("AGRFORTFISH" = "Agriculture and Fishery"))
coun_ava_df$activity<- plyr::revalue(coun_ava_df$activity, c("CONSTR" = "Construction"))
coun_ava_df$activity<- plyr::revalue(coun_ava_df$activity, c("FINANCEINS" = "Finance and Insurance"))
coun_ava_df$activity<- plyr::revalue(coun_ava_df$activity, c("INDUSENRG" = "Industry and Energy"))
coun_ava_df$activity<- plyr::revalue(coun_ava_df$activity, c("INFCOMM" = "Information Communication"))
coun_ava_df$activity<- plyr::revalue(coun_ava_df$activity, c("MFG" = "Manufacturing"))
coun_ava_df$activity<- plyr::revalue(coun_ava_df$activity, c("OTHSERVACT" = "Other Service Activities"))
coun_ava_df$activity<- plyr::revalue(coun_ava_df$activity, c("PROSCISUPP" = "Profesional and Scientific Support Services"))
coun_ava_df$activity<- plyr::revalue(coun_ava_df$activity, c("PUBADMINEDUSOC" = "Public")) # Public Administration, Defense, Education, Health, Social Work
coun_ava_df$activity<- plyr::revalue(coun_ava_df$activity, c("REALEST" = "Real Estate"))
coun_ava_df$activity<- plyr::revalue(coun_ava_df$activity, c("SERV" = "Services"))
coun_ava_df$activity<- plyr::revalue(coun_ava_df$activity, c("TOT" = "Total Growth"))
coun_ava_df$activity<- plyr::revalue(coun_ava_df$activity, c("WHLEHTELTRANSP" = "Wholesale, Retail, Trade, Transport, Accomodation"))


em_tax_df$activity<- plyr::revalue(em_tax_df$subject, c("AGR" = "Agriculture and Fishery"))
em_tax_df$activity<- plyr::revalue(em_tax_df$subject, c("ENRG" = "Energy"))
em_tax_df$activity<- plyr::revalue(em_tax_df$subject, c("TOT" = "Total Growth"))
em_tax_df$activity<- plyr::revalue(em_tax_df$subject, c("OTH" = "Other"))
em_tax_df$activity<- plyr::revalue(em_tax_df$subject, c("MOTORVEH" = "Wholesale, Retail, Trade, Transport, Accomodation"))


countries_ce <- unique(ce_df$country)
countries_ce
countries_df <- unique(coun_ava_df$location)
countries_df

em_tot_tax_df <- em_tax_df %>% 
  filter(measure == "PC_TOT_TAX")
  

# PC(?percent?) value 
pc_val_added <- coun_ava_df %>% 
  filter(measure == "PC_VA")

# AGRWTH value 
agr_val_added <- coun_ava_df %>% 
  filter(measure == "AGRWTH")


# Per Activity Value added DF(global value added per year)
int_ava_df <- pc_val_added %>% 
  dplyr::group_by(activity, year) %>% 
  dplyr::summarise(average_val = mean(value))


int_ava_df %>%
  ggplot(
    aes(
      x = (year),
      y = (average_val),
      color = activity
    )
  ) +
  geom_point(size = 2) +
  geom_smooth(se = FALSE, method = lm) +
  facet_grid(rows = vars(activity)) +
  labs(
    x = "Year",
    y = "Value Added",
    colour = 'Activity Category',
    title = "Economical Value Added vs Year"
  )

# Per Average Value added DF(global value added per year)
coun_ava_df <- pc_val_added %>% 
  dplyr::group_by(location, activity, year) %>% 
  dplyr::summarise(average_val = mean(value))
  
# Emission and value added merged df
em_act_val_merged_df <- dplyr::left_join(ce_df, coun_ava_df, by = c("country" = "location", "year" = "year"))

# Environmental tax and value added merged df
env_tax_merged_df <- dplyr::left_join(em_tax_df, coun_ava_df, by = c("location" = "location", "year" = "year"))








