
library(plyr)
library(dplyr)
library(countrycode)
library(tidyr)
library(readxl)
library(janitor)
library(ggplot2)
library(skimr)
library(stringr)
library(ggrepel)

install.packages("countrycode")
library(countrycode)


country_emissions_filename <- "data/raw/CAIT-Country-GHG-Emissions.csv"

# Value added reflects the value generated by producing goods and services, 
# Value Added = (value of output - value of intermediate consumption)/total value added)
# https://data.oecd.org/natincome/value-added-by-activity.htm#indicator-chart
activity_value_filename <- "data/raw/value_added_per_act.csv"

# http://www.lse.ac.uk/GranthamInstitute/climate-change-laws-of-the-world/
regulation_filename <- "data/raw/law_search/data.csv"

# https://data.oecd.org/envpolicy/environmental-tax.htm
emission_tax_filename <- "data/raw/emission_tax.csv"

# https://data.oecd.org/emp/employment-by-activity.htm
empl_per_act_filename <- "data/raw/employment_per_act.csv"

# SECTOR DEFINITION (Source: http://fenixservices.fao.org/faostat/static/documents/EM/EM_e.pdf )

# Energy (energy, manufacturing and construction industries and fugitive emissions): 
# emissions are inclusive of public heat and electricity production; 
# other energy industries; fugitive emissions from solid fuels, oil and gas, manufacturing industries and construction.
# Transport: domestic aviation, road transportation, rail transportation, domestic navigation, other transportation.
# International bunkers: international aviation; international navigation/shipping.
# Residential, commercial, institutional and AFF: Residential and other sectors.
# Industry (industrial processes and product use):
# production of minerals, chemicals, metals, pulp/paper/food/drink, halocarbons, refrigeration and air conditioning; aerosols and solvents; semicondutor/electronics manufacture; electrical equipment.
# Waste: solid waste disposal; wastewater handling; waste incineration; other waste handling.
# Agriculture: methane and nitrous oxide emissions from enteric fermentation; manure management; rice cultivation; synthetic fertilizers; manure applied to soils; manure left on pasture; crop residues; burning crop residues, savanna and cultivation of organic soils.
# Land use: emissions from the net conversion of forest; cropland; grassland and burning biomass for agriculture or other uses.
# Other sources: fossil fuel fires; indirect nitrous oxide from non-agricultural NOx and ammonia; other anthropogenic sources

# CO2 per sector
co2_per_sect <- "data/raw/emission_per_sect/global-carbon-dioxide-emissions-by-sector.csv"

# methane per sector
meth_per_sect <- "data/raw/emission_per_sect/methane-emissions-by-sector-gg-coe.csv"

# Nitrous Oxide per sector
no2_per_sect <- "data/raw/emission_per_sect/nitrous-oxide-emissions-by-sector.csv"

# Greenhouse gas emission per sector
gge_per_sect <- "data/raw/emission_per_sect/greenhouse-gas-emissions-by-sector.csv"

processCsvData <- function(csv_filename) {
  csv_df <- read.csv(csv_filename) %>% 
    clean_names() %>% 
    na.omit()
  return(csv_df)
}

# Employment per activity filename
empl_per_act_df <- processCsvData(empl_per_act_filename)

# Country Emission DF (Total GHG)
# Don't worry about negative emissions : https://www.nrcan.gc.ca/our-natural-resources/forests-forestry/state-canadas-forests-report/how-does-disturbance-shape-canad/indicator-carbon-emissions-removals/16552
ghg_emission <- processCsvData(gge_per_sect) %>% 
  mutate(emission_sum = rowSums(.[3:12]))

# Country Emission DF (mtCO2)
ce_df <-  read.csv(country_emissions_filename, skip=2) %>% 
  clean_names()

# Regulation per country DF
reg_df <- processCsvData(regulation_filename)

# Environmental tax per country DF
env_tax_df <- processCsvData(emission_tax_filename) %>% 
  dplyr::rename(year = time) %>% 
  select(-starts_with("indicator")) %>%
  dplyr::mutate(location = countrycode::countrycode(location, 'iso3c', 'country.name.en'))

# Per Country Activity Value Added DF
coun_ava_df <- processCsvData(activity_value_filename) %>% 
  dplyr::rename(activity = subject) %>% 
  dplyr::rename(year = time) %>% 
  select(-starts_with("indicator")) %>% # Remove Indicator 
  dplyr::mutate(location = countrycode::countrycode(location, 'iso3c', 'country.name.en'))

# Rename value added sector names to convene to emission dataset sector name
coun_ava_df$activity <- plyr::revalue(coun_ava_df$activity, c("AGRFORTFISH" = "Agriculture and Fishery"))
coun_ava_df$activity <- plyr::revalue(coun_ava_df$activity, c("CONSTR" = "Construction"))
coun_ava_df$activity <- plyr::revalue(coun_ava_df$activity, c("FINANCEINS" = "Finance and Insurance"))
coun_ava_df$activity <- plyr::revalue(coun_ava_df$activity, c("INDUSENRG" = "Industry and Energy")) 
coun_ava_df$activity <- plyr::revalue(coun_ava_df$activity, c("INFCOMM" = "Information Communication"))
coun_ava_df$activity <- plyr::revalue(coun_ava_df$activity, c("MFG" = "Manufacturing"))
coun_ava_df$activity <- plyr::revalue(coun_ava_df$activity, c("OTHSERVACT" = "Other Service Activities"))
coun_ava_df$activity <- plyr::revalue(coun_ava_df$activity, c("PROSCISUPP" = "Profesional and Scientific Support Services"))
coun_ava_df$activity <- plyr::revalue(coun_ava_df$activity, c("PUBADMINEDUSOC" = "Public")) # Public Administration, Defense, Education, Health, Social Work
coun_ava_df$activity <- plyr::revalue(coun_ava_df$activity, c("REALEST" = "Real Estate"))
coun_ava_df$activity <- plyr::revalue(coun_ava_df$activity, c("SERV" = "Services"))
coun_ava_df$activity <- plyr::revalue(coun_ava_df$activity, c("TOT" = "Total Growth"))
coun_ava_df$activity <- plyr::revalue(coun_ava_df$activity, c("WHLEHTELTRANSP" = "Transport, Accomodation"))


# Rename Environment Tax Sectors
env_tax_df$subject <- plyr::revalue(env_tax_df$subject, c("ENRG" = "Energy"))
env_tax_df$subject <- plyr::revalue(env_tax_df$subject, c("MOTORVEH" = "Motored Vehicles"))
env_tax_df$subject <- plyr::revalue(env_tax_df$subject, c("OTH" = "Other"))
env_tax_df$subject <- plyr::revalue(env_tax_df$subject, c("TOT" = "Total Environmental Tax Generated"))



countries_ce <- unique(ce_df$country)
countries_ce
countries_df <- unique(coun_ava_df$location)
countries_df

# Add columns to emission data frame to convene to GDP growth per sector df
ce_df <- ce_df %>% 
  mutate(agriculture_em = agriculture_mt_co2e) 

  

# Get Countries of Interest

# Avg emissions of all types per country (mtCO2)
country_avg_emissions <- ce_df %>% 
  select(-year) %>% 
  filter(country != 'World', !str_detect(country, 'European Union')) %>% 
  group_by(country) %>% 
  summarise_each(list(mean = mean))

ce_df_freq <- data.frame(table(ce_df$country))

# Avg emission for all GHG (in tonnes of ghg)
ghg_avg_emissions -> ghg_emission %>% 
  group_by(entity) 

year_freq <- data.frame(table(ghg_emission$entity))
  
  

 

# Barplot of top 20 countries avg ghg emission
country_avg_emissions %>% 
  rename(avg_ghg_emissions = total_ghg_emissions_including_land_use_change_and_forestry_mt_co_e_mean) %>% 
  top_n(20, wt=avg_ghg_emissions) %>% 
  ggplot(aes(reorder(country, avg_ghg_emissions), avg_ghg_emissions)) +
  geom_bar(stat='identity') +
  coord_flip() + 
  labs(
    title = 'Top 20 countries based on their average GHG emissions',
    x = 'Country',
    y = 'Average GHG emission per year (MtCO2e)'
  ) +
  theme_hc()

# Thus these our countries of interest
countries_of_interest <-
  tribble(
    ~country,
    'United States',
    'China',
    'India',
    'Japan',
    'Brazil',
    'Canada'
  )


# Measure used should be Percent of total tax
env_tot_tax_df <- env_tax_df %>% 
  filter(measure == "PC_TOT_TAX")
  

# PC(?percent?) value 
# pc_val_added <- coun_ava_df %>% 
  # filter(measure == "PC_VA")

# AGRWTH value 
growth_added <- coun_ava_df %>% 
  filter(measure == "AGRWTH")


# Per Activity Value added DF(global value added per year)
int_ava_df <- growth_added %>% 
  dplyr::group_by(activity, year) %>% 
  dplyr::summarise(average_val = mean(value))


# Start with different subsectors for same country 

# International Average value added per year
int_ava_df %>%
  ggplot(
    aes(
      x = (year),
      y = (average_val),
      color = activity
    )
  ) +
  geom_point(size = 2) +
  geom_smooth(se = FALSE, method = lm) +
  facet_grid(rows = vars(activity)) +
  labs(
    x = "Year",
    y = "Value Added",
    colour = 'Activity Category',
    title = "Economical Value Added vs Year"
  )

# Per Average Value added DF(global value added per year)
coun_ava_df <- growth_added %>% 
  dplyr::group_by(location, activity, year)
  # %>% dplyr::summarise(average_val = mean(value))
  
# Emission and growth per sector merged df
em_growth_merged_df <- dplyr::left_join(ce_df, coun_ava_df, by = c("country" = "location", "year" = "year")) 

# Emission and Env tax merged df (TO NOT BE USED ?YET?)
# em_envtax_merged_df <- dplyr::left_join(ce_df, env_tot_tax_df, by = c("country" = "location", "year" = "year"))

# Environmental tax and value added merged df (TO NOT BE USED ?YET?)
# env_tax_merged_df <- dplyr::left_join(env_tax_df, coun_ava_df, by = c("location" = "location", "year" = "year"))

# Agriculture and Fishery Growth Contribution

agr_growth_df <- em_growth_merged_df %>% 
  filter(activity == "Agriculture and Fishery")

# "Other" Tax revenue (TO NOT BE USED ?YET?)
# oth_tax_df <- env_tot_tax_df %>% 
#   filter(subject == "Other") %>% 
#   select(c("location", "value", "year")) %>% 
#   rename("total_env_tax" = "value")


aus_growth_em <- agr_growth_df %>% filter(country == "Australia")

# First let's assume that Value added and environmental tax are independent to one another
# to perform Pearson corelation test
# We also assume there is a linear relationship between the two

# Assume That both variables are continuous and linearly related (appears linear barring outliers)
plot(aus_growth_em$value, aus_growth_em$agriculture_em)

# Assume variables follow a bivariate normal distribution
qqnorm(aus_growth_em$value)
qqline(aus_growth_em$value)

qqnorm(aus_growth_em$agriculture_em)
qqline(aus_growth_em$agriculture_em)

# Assume variances are homogeneous (no cone shape scatter plot)

# No Major outliers (check scatter plot)

# Correlation test
cor.test(aus_growth_em$value, aus_growth_em$agriculture_em, method = "pearson", data=aus_val_tax)

# Output -> Non Significant negative corelation

# Australia value added per year for Agriculture Sector
aus_val_tax %>%
  ggplot(
    aes(
      x = (year),
      y = (value),
      color = activity
    )
  ) +
  geom_point(size = 2) +
  geom_smooth(se = FALSE, method = lm) +
  facet_grid(rows = vars(activity)) +
  labs(
    x = "Year",
    y = "Value Added",
    colour = 'Activity Category',
    title = "Economical Value Added vs Year In Australia"
  )

aus_val_tax %>% 
  ggplot(
    aes(
      x = (year),
      y = (total_env_tax),
      color = activity
    )
  ) +
  geom_point(size = 2) +
  geom_smooth(se = FALSE, method = lm) +
  facet_grid(rows = vars(activity)) +
  labs(
    x = "Year",
    y = "Environment Tax Income",
    colour = 'Activity Category',
    title = "Environment Tax Income vs Year In Australia"
  )



