---
title: "`r params$indicator_name`"
author: "Shaafici ALi"
date: "`r Sys.time()`"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    
params:
  series_code: 'y'
  topic: 'y'
  indicator_name: 'y'
  short_definition: 'y'
  long_definition: 'y'
  unit_of_measure: 'y'
  periodicity: 'y'
  base_period: 'y'
  other_notes: 'y'
  aggregation_method: 'y'
  limitations_and_exceptions: 'y'
  notes_from_original_source: 'y'
  general_comments, source: 'y'
  statistical_concept_and_methodology: 'y'
  development_relevance: 'y'
  related_source_links: 'y'
  other_web_links: 'y'
  related_indicators: 'y'
  license_type: 'y'
  general_comments: 'y'
  source: 'y'
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
library(dplyr)
library(tidyr)
```
```{r}
Longdefinition <- params$long_definition
GeneralComments <- params$general_comments
StatisticalConcepts <- params$statistical_concept_and_methodology
DevelopmentRelevance <- params$development_relevance
Limitations <- params$limitations_and_exceptions
OriginalSourceNotes <- params$notes_from_original_source
OtherNotes <- params$other_notes
Source <- params$source
SeriesCode <- params$series_code
if(is.na(GeneralComments)){
  GeneralComments <- "The author did not provide general comments for this metric"
}

if(is.na(StatisticalConcepts)){
  StatisticalConcepts<- "The author did not discuss statistical concepts and methodology used"
}

if(is.na(DevelopmentRelevance)){
  DevelopmentRelevance <- "The author did not how this metric is relevant to development"
}

if(is.na(Limitations)){
  Limitations <-"THe author did not discuss possible limitations"
}

if(is.na(OriginalSourceNotes)){
  OriginalSourceNotes <-"The author did not provide original source notes"
}

if(is.na(OtherNotes)){
  OtherNotes <- "The author does not have other notes"
}
```


Series Code: `r SeriesCode`

#Long Definition
`r Longdefinition`


#Statistical Concept and methodology
`r StatisticalConcepts`

#Development relevance
`r DevelopmentRelevance`

#limitations and exceptions
`r Limitations`

#General Comments
`r GeneralComments`

#Notes from original source
`r OriginalSourceNotes`

#Other notes
`r OtherNotes`


#Source
`r Source`